name: Go Tests
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout your project with git
      - name: Checkout
        uses: actions/checkout@v2

      # Install Go on the VM running the action.
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # install deps using go install
      - name: Install test dependencies
        run: |
          go install gotest.tools/gotestsum@v0.4.2
          wget --no-verbose https://releases.hashicorp.com/nomad/1.2.6/nomad_1.2.6_linux_amd64.zip
          unzip nomad_1.2.6_linux_amd64.zip
          cp nomad /usr/local/bin
          
      # Run tests with nice formatting. Save the original log in /tmp/gotest.log
      - name: Run tests
        run: |
          gotestsum --format=pkgname-and-test-fails -- ./...

