name: Go Tests
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Go
        uses: hashicorp/setup-golang@v1

      # install deps using go install
      - name: Install test dependencies
        run: |
          go install gotest.tools/gotestsum@latest
          make test-certs

      # install nomad
      - name: Install Nomad
        run : |
          sudo apt -y install wget gpg coreutils
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt -y install nomad
          
      # Run tests with nice formatting. Save the original log in /tmp/gotest.log
      - name: Run tests
        run: |
          gotestsum -f testname --jsonfile /tmp/test-output.log -- ./...

      # Upload the original go test log as an artifact for later review.
      - name: Upload test log
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: test-log
          path: /tmp/test-output.log
          if-no-files-found: error
